### ISSUE TITLE
new maintainer

### ISSUE THREAD

**Issue by slashformotion** [loikein/hugo-tufte#5]
Hello, 
If you plan on maintaining this theme, i can mention your fork on the readme and archive my repo. 
I don't plan on doing any more development on it.

**Comment by slashformotion** [comment]
well can I put a link in my readme pointing to your repo ? As long as it is in the tufte spirit, i think it's ok

**Comment by loikein** [comment]
Yes, that would be great. Please also mention that it introduces multiple breaking changes (mainly to the shortcodes). Thanks a lot!
